triggers:
  - type: meya.cms_nlu
    properties:
        detect_language: true
        space: faq
  - type: meya.cms_nlu
    properties:
        detect_language: true
        space: faq
name: faq
states:
    answer:
        component: meya.cms_text