triggers:
  - type: meya.api_ai
    properties:
        intent_regex: ^(smalltalk\..+)|(hello)$
        language: en
        client_access_token: 3293132b7bf14c989a7cc8f81734a7d0
name: smalltalk
intents:
    smalltalk.greetings.hello: hello
    smalltalk.agent.can_you_help: help
states:
    default:
        component: meya.text
        properties:
            text: "{{ flow.fulfillment.speech }}"
        return: true
    hello:
        component: meya.text
        properties:
            text: "{{ cms.copy.hello }}"
        return: true
    help:
        component: meya.text
        properties:
            text: "{{ cms.copy.help }}"
        return: true